/*

The WINTER-API is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

The WINTER-API is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the WINTER-API.  If not, see <http://www.gnu.org/licenses/>.

*/

/* Generated By:JavaCC: Do not edit this line. SPARQLPatternParserTreeConstants.java Version 5.0 */
package de.uniko.west.winter.utils.parser.triplepatternparser;

public interface SPARQLPatternParserTreeConstants
{
  public int JJTQUERYCONTAINER = 0;
  public int JJTVOID = 1;
  public int JJTTRIPLESSAMESUBJECT = 2;
  public int JJTPROPERTYLIST = 3;
  public int JJTVAR = 4;
  public int JJTIRI = 5;
  public int JJTOBJECTLIST = 6;
  public int JJTCOLLECTION = 7;
  public int JJTBLANKNODEPROPERTYLIST = 8;
  public int JJTQNAME = 9;
  public int JJTBLANKNODE = 10;
  public int JJTRDFLITERAL = 11;
  public int JJTNUMERICLITERAL = 12;
  public int JJTTRUE = 13;
  public int JJTFALSE = 14;
  public int JJTSTRING = 15;


  public String[] jjtNodeName = {
    "QueryContainer",
    "void",
    "TriplesSameSubject",
    "PropertyList",
    "Var",
    "IRI",
    "ObjectList",
    "Collection",
    "BlankNodePropertyList",
    "QName",
    "BlankNode",
    "RDFLiteral",
    "NumericLiteral",
    "True",
    "False",
    "String",
  };
}
/* JavaCC - OriginalChecksum=4e699cb81d5c2b701b303971fb004cc6 (do not edit this line) */
